Better & more informative logging and error handling (#130)
* Meaningful information and log grouping

* Better structured logging & error messages

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -120,8 +120,14 @@ jobs:
       - name: Build
         run: |
           foreach($target in ($env:BUILD_TARGETS).Split(',')) {
-            echo $target
+            echo "::group::Build for $target target"
             cargo build $(if($target -ne 'default') {"--target=$target"} ) 
+            echo "::endgroup::"
+
+            if (!$?) { 
+              echo "::error::Build for $target target" ;
+              throw "Last exit code $LASTEXITCODE"
+            }
           }
 
       # For each target in the BUILD_TARGETS comma-separated list, run cargo test with appropriate target
@@ -129,8 +135,14 @@ jobs:
       - name: Run tests
         run: |
           foreach($target in ($env:BUILD_TARGETS).Split(',')) {
-            echo $target
+            echo "::group::Test for $target target"
             cargo test $(if($target -ne 'default') {"--target=$target"} ) -- --nocapture
+            echo "::endgroup::"
+            
+            if (!$?) { 
+              echo "::error::Test for $target target" ;
+              throw "Last exit code $LASTEXITCODE"
+            }
           }
 
 
@@ -244,18 +256,22 @@ jobs:
       - name: Build
         run: |
           foreach($target in ($env:BUILD_TARGETS).Split(',')) {
-            echo $target
+            echo "::group::Build extendr-api for $target target"
             cargo build --manifest-path extendr-api/Cargo.toml --features tests-all $(if($target -ne 'default') {"--target=$target"} )
+            echo "::endgroup::"
+
             if (!$?) { 
-              echo "::error::$target" ;
+              echo "::error::Build extendr-api for $target target" ;
               throw "Last exit code $LASTEXITCODE"
             }
           }
           foreach($target in ($env:BUILD_TARGETS).Split(',')) {
-            echo $target
+            echo "::group::Build extendr-engine for $target target"
             cargo build --manifest-path extendr-engine/Cargo.toml --features tests-all $(if($target -ne 'default') {"--target=$target"} ) 
+            echo "::endgroup::"
+
             if (!$?) { 
-              echo "::error::$target" ;
+              echo "::error::Build extendr-engine for $target target" ;
               throw "Last exit code $LASTEXITCODE"
             }
           }
@@ -263,34 +279,42 @@ jobs:
       - name: Run tests
         run: |
           foreach($target in ($env:BUILD_TARGETS).Split(',')) {
-            echo $target
+            echo "::group::Test extendr-engine \w tests-all for $target target"
             cargo test --manifest-path extendr-engine/Cargo.toml --features tests-all $(if($target -ne 'default') {"--target=$target"} ) -- --nocapture 
+            echo "::endgroup::"
+
             if (!$?) { 
-              echo "::error::$target" ;
+              echo "::error::Test extendr-engine \w tests-all for $target target" ;
               throw "Last exit code $LASTEXITCODE"
             }
           }
           foreach($target in ($env:BUILD_TARGETS).Split(',')) {
-            echo $target
+            echo "::group::Test extendr-api \w tests-all for $target target"
             cargo test --manifest-path extendr-api/Cargo.toml --features tests-all $(if($target -ne 'default') {"--target=$target"} ) -- --nocapture 
+            echo "::endgroup::"
+
             if (!$?) { 
-              echo "::error::$target" ;
+              echo "::error::Test extendr-api \w tests-all for $target target" ;
               throw "Last exit code $LASTEXITCODE"
             }
           }
-          foreach($target in ($env:BUILD_TARGETS).Split(',')) {
-            echo $target
+          foreach($target in ($env:BUILD_TARGETS).Split(',')) {            
+            echo "::group::Test extendr-api \w tests-minimal for $target target"
             cargo test --manifest-path extendr-api/Cargo.toml --features tests-minimal $(if($target -ne 'default') {"--target=$target"} ) -- --nocapture
+            echo "::endgroup::"
+
             if (!$?) { 
-              echo "::error::$target" ;
+              echo "::error::Test extendr-api \w tests-minimal for $target target" ;
               throw "Last exit code $LASTEXITCODE"
             }
           }
           foreach($target in ($env:BUILD_TARGETS).Split(',')) {
-            echo $target
+            echo "::group::Test extendr-macros for $target target"
             cargo test --manifest-path extendr-macros/Cargo.toml  $(if($target -ne 'default') {"--target=$target"} ) -- --nocapture
+            echo "::endgroup::"
+
             if (!$?) { 
-              echo "::error::$target" ;
+              echo "::error::Test extendr-macros for $target target" ;
               throw "Last exit code $LASTEXITCODE"
             }
           }
