Better structured logging & error messages

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -120,8 +120,14 @@ jobs:
       - name: Build
         run: |
           foreach($target in ($env:BUILD_TARGETS).Split(',')) {
-            echo $target
+            echo "::group::Build for $target target"
             cargo build $(if($target -ne 'default') {"--target=$target"} ) 
+            echo "::endgroup::"
+
+            if (!$?) { 
+              echo "::error::Build for $target target" ;
+              throw "Last exit code $LASTEXITCODE"
+            }
           }
 
       # For each target in the BUILD_TARGETS comma-separated list, run cargo test with appropriate target
@@ -129,8 +135,14 @@ jobs:
       - name: Run tests
         run: |
           foreach($target in ($env:BUILD_TARGETS).Split(',')) {
-            echo $target
+            echo "::group::Test for $target target"
             cargo test $(if($target -ne 'default') {"--target=$target"} ) -- --nocapture
+            echo "::endgroup::"
+            
+            if (!$?) { 
+              echo "::error::Test for $target target" ;
+              throw "Last exit code $LASTEXITCODE"
+            }
           }
 
 
@@ -249,7 +261,7 @@ jobs:
             echo "::endgroup::"
 
             if (!$?) { 
-              echo "::error::$target" ;
+              echo "::error::Build extendr-api for $target target" ;
               throw "Last exit code $LASTEXITCODE"
             }
           }
@@ -257,9 +269,9 @@ jobs:
             echo "::group::Build extendr-engine for $target target"
             cargo build --manifest-path extendr-engine/Cargo.toml --features tests-all $(if($target -ne 'default') {"--target=$target"} ) 
             echo "::endgroup::"
-            
+
             if (!$?) { 
-              echo "::error::$target" ;
+              echo "::error::Build extendr-engine for $target target" ;
               throw "Last exit code $LASTEXITCODE"
             }
           }
@@ -272,7 +284,7 @@ jobs:
             echo "::endgroup::"
 
             if (!$?) { 
-              echo "::error::$target" ;
+              echo "::error::Test extendr-engine \w tests-all for $target target" ;
               throw "Last exit code $LASTEXITCODE"
             }
           }
@@ -282,7 +294,7 @@ jobs:
             echo "::endgroup::"
 
             if (!$?) { 
-              echo "::error::$target" ;
+              echo "::error::Test extendr-api \w tests-all for $target target" ;
               throw "Last exit code $LASTEXITCODE"
             }
           }
@@ -292,7 +304,7 @@ jobs:
             echo "::endgroup::"
 
             if (!$?) { 
-              echo "::error::$target" ;
+              echo "::error::Test extendr-api \w tests-minimal for $target target" ;
               throw "Last exit code $LASTEXITCODE"
             }
           }
@@ -302,7 +314,7 @@ jobs:
             echo "::endgroup::"
 
             if (!$?) { 
-              echo "::error::$target" ;
+              echo "::error::Test extendr-macros for $target target" ;
               throw "Last exit code $LASTEXITCODE"
             }
           }
